"""Report export: JSON and a polished markdown scorecard for benchmark results."""
from __future__ import annotations

import json

from .benchmark import BenchmarkResult
from .benchmark import TaskResult

CHECK = "✅"
CROSS = "❌"
WARN = "⚠️"
EM_DASH = "—"
BAR_FILLED = "█"
BAR_EMPTY = "░"
BAR_WIDTH = 10


def to_json(result: BenchmarkResult, pretty: bool = True) -> str:
    """Serialize a BenchmarkResult to a JSON string."""
    data = result.to_dict()
    if pretty:
        return json.dumps(data, indent=2, ensure_ascii=False)
    return json.dumps(data, ensure_ascii=False, separators=(",", ":"))


def _fmt_score(x: float) -> str:
    return f"{x:.2f}"


def _fmt_delta(x: float) -> str:
    if abs(x) < 1e-9:
        return "±0.00"
    sign = "+" if x > 0 else "-"
    arrow = "▲" if x > 0 else "▼"
    return f"{arrow} {sign}{abs(x):.2f}"


def _pass_mark(passed: bool) -> str:
    return CHECK if passed else CROSS


def _score_bar(score: float, width: int = BAR_WIDTH) -> str:
    """Render a 0..1 score as a block bar, e.g. ``█████░░░░░ 50%``."""
    clamped = max(0.0, min(1.0, float(score)))
    filled = int(round(clamped * width))
    bar = BAR_FILLED * filled + BAR_EMPTY * (width - filled)
    return f"{bar} {clamped:.0%}"


def _task_mark(t: TaskResult) -> str:
    return CHECK if t.passed else (CROSS if not t.error else WARN)


def _version_footer() -> str:
    try:
        from . import __version__

        return f"Generated by agentbench {__version__}"
    except Exception:  # pragma: no cover - version import should always succeed
        return "Generated by agentbench"


def _scorecard(result: BenchmarkResult) -> list[str]:
    s = result.summary()
    tokens = s.get("tokens", {})
    total_tokens = tokens.get("total", 0)
    lines: list[str] = []
    lines.append("## 📊 Scorecard")
    lines.append("")
    lines.append("| | |")
    lines.append("|---|---|")
    lines.append(
        f"| **Tasks** | {s['task_count']} · {CHECK} {s['passed']} "
        f"· {CROSS} {s['failed']} · {WARN} {s['errors']} |"
    )
    lines.append(f"| **Mean score** | `{_score_bar(result.mean_score)}` ({_fmt_score(result.mean_score)}) |")
    lines.append(f"| **Pass rate** | `{_score_bar(result.pass_rate)}` |")
    lines.append(f"| **p95 latency** | {result.p95_latency:.3f}s |")
    lines.append(
        f"| **Tokens** | {tokens.get('prompt', 0):,} in · "
        f"{tokens.get('completion', 0):,} out · **{total_tokens:,} total** |"
    )
    lines.append("")
    return lines


def _tasks_table(result: BenchmarkResult) -> list[str]:
    lines: list[str] = []
    lines.append("## Tasks")
    lines.append("")
    lines.append("| # | Task | Score | | Pass | Latency |")
    lines.append("|---:|---|---:|:---|:---:|---:|")
    for i, t in enumerate(result.tasks, start=1):
        mark = _task_mark(t)
        score_cell = _fmt_score(t.score)
        if t.error:
            score_cell += f" · `{t.error}`"
        lines.append(
            f"| {i} | {t.task_name} | {score_cell} | `{_score_bar(t.score)}` | {mark} | {t.latency_s:.3f}s |"
        )
    lines.append("")
    return lines


def _rule_detail(result: BenchmarkResult) -> list[str]:
    lines: list[str] = []
    lines.append("## Rule detail")
    lines.append("")
    for t in result.tasks:
        mark = _task_mark(t)
        lines.append(f"### {mark} {t.task_name} — {_fmt_score(t.score)}")
        lines.append("")
        if t.error:
            lines.append(f"> {WARN} **error:** {t.error}")
            lines.append("")
            continue
        if not t.rules:
            lines.append("_no rubric rules evaluated_")
            lines.append("")
            continue
        for r in t.rules:
            rmark = "✓" if r.passed else "✗"
            weight = f" · w={r.weight:g}" if r.weight != 1.0 else ""
            lines.append(f"- {rmark} `{r.name}`{weight}: {r.detail or '—'}")
        lines.append("")
    return lines


def _comparison(result: BenchmarkResult, other: BenchmarkResult) -> list[str]:
    a, b = result, other
    lines: list[str] = []
    lines.append("## 🆚 Comparison")
    lines.append("")
    lines.append(f"**{a.model}** (A) vs **{b.model}** (B)")
    lines.append("")
    delta = a.mean_score - b.mean_score
    lines.append(
        f"- **Mean:** A `{_score_bar(a.mean_score)}` vs B `{_score_bar(b.mean_score)}` "
        f"· Δ **{_fmt_delta(delta)}**"
    )
    lines.append(
        f"- **Pass rate:** A `{_score_bar(a.pass_rate)}` vs B `{_score_bar(b.pass_rate)}`"
    )
    lines.append("")
    lines.append("| # | Task | A | B | Δ | A pass | B pass |")
    lines.append("|---:|---|---:|---:|:---:|:---:|:---:|")
    b_by_id = {t.task_id: t for t in b.tasks}
    a_ids = {t.task_id for t in a.tasks}
    idx = 0
    for ta in a.tasks:
        idx += 1
        tb = b_by_id.get(ta.task_id)
        if tb is None:
            lines.append(
                f"| {idx} | {ta.task_name} | {_fmt_score(ta.score)} | {EM_DASH} | {EM_DASH} "
                f"| {_pass_mark(ta.passed)} | {EM_DASH} |"
            )
            continue
        d = ta.score - tb.score
        lines.append(
            f"| {idx} | {ta.task_name} | {_fmt_score(ta.score)} | {_fmt_score(tb.score)} "
            f"| {_fmt_delta(d)} | {_pass_mark(ta.passed)} | {_pass_mark(tb.passed)} |"
        )
    for tb in b.tasks:
        if tb.task_id in a_ids:
            continue
        idx += 1
        lines.append(
            f"| {idx} | {tb.task_name} | {EM_DASH} | {_fmt_score(tb.score)} | {EM_DASH} "
            f"| {EM_DASH} | {_pass_mark(tb.passed)} |"
        )
    lines.append("")
    return lines


def to_markdown(
    result: BenchmarkResult,
    other: BenchmarkResult | None = None,
    title: str | None = None,
) -> str:
    """Render a BenchmarkResult (optionally compared to ``other``) as markdown.

    Produces a scorecard summary, a per-task table with score bars, and a
    rule-by-rule breakdown. When ``other`` is given, a side-by-side
    comparison is emitted instead of the single-task table.
    """
    lines: list[str] = []
    lines.append(f"# {title or f'🏁 agentbench — {result.model}'}")
    lines.append("")
    lines.append(
        f"> **Endpoint:** `{result.endpoint}` · **Model:** `{result.model}` · **Started:** {result.started_at}"
    )
    lines.append("")

    lines.extend(_scorecard(result))
    if other is not None:
        lines.extend(_comparison(result, other))
    else:
        lines.extend(_tasks_table(result))
    lines.extend(_rule_detail(result))

    lines.append("---")
    lines.append(f"*{_version_footer()}*")
    return "\n".join(lines)
